php:
  build: .
  container_name: App2
  ports:
   - "8888:80"
   - "443:443"
  volumes:
   - ./www:/var/www/html
  links:
   - db2
  
db2:
  image: mysql:5.7
  volumes:
   - /var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=phprs
   - MYSQL_DATABASE=phprs
